name: Native builds (prebuild + pods/gradle)

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ios:
    runs-on: macos-13
    defaults:
      run:
        working-directory: app
    steps:
      - uses: actions/checkout@v4
      # Dependency review runs only in PR workflows, skipped on push
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'
      - name: Enable Corepack & install deps
        run: |
          corepack enable
          yarn install --frozen-lockfile
      - name: Prebuild iOS
        run: CI=1 npx expo prebuild --platform ios --no-install
      - name: Install CocoaPods
        run: |
          cd ios
          pod install --repo-update --deployment

  android:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app
    steps:
      - uses: actions/checkout@v4
      # Dependency review runs only in PR workflows, skipped on push
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'yarn'
      - name: Enable Corepack & install deps
        run: |
          corepack enable
          yarn install --frozen-lockfile
      - name: Prebuild Android
        run: CI=1 npx expo prebuild --platform android --no-install
      - name: Build Gradle (assembleDebug)
        run: |
          cd android
          ./gradlew assembleDebug --no-daemon 